### PR TITLE
Added the option for a dark and a light theme.

### PR DESCRIPTION
**Pull request by Kablion**
Now on every Widget is a custom option to change the theme. When changed every other Widget updates.
I changed the way colors are put in most meters.
Instead of constant colors like SolidBlack or SolidWhite now the colors are divided into Foreground and Background. I changed almost every SolidColor / FontColor Options. 
It's a hugh edit and thats why I'm not 100% sure I didn't mess something up.
But as far as my testing goes every Widget looks good in both themes.
If there are any suggested color changes go for it. It should be pretty easy to change colors because I think every color is defined in the variables.ini

**Dark Theme (Should Look like the way all widgets looked before this edit):**

W10W-Dark-Theme

**Light Theme:**

W10W-Light-Theme

### CODE REVIEW

**Comment by MinhThienDX** [comment]
Wow this is big.
Good job as always 💯👏👌
I have only 1 suggestion: Do smaller commit.

For example, in the edfa56603430afcb86d3e633e2e6c8210b5817f8 commit, you can break down to multiple smaller commits like so:
1. Commit all files in @Resources folder (this is the foundation)
2. Commit all files in Battery folder (this skin now can use committed variables in step 1)
3. Commit all files in Cryptometer folder
4. And so on

That way, it will be very easy to revert commit for particular part of the skin.
Thank you for your contribution. ❤

**Comment by Kablion** [comment]
Thanks for the suggestion. I'm relatively new to Git. 
Do you think the work on Win10Widgets is something we should even continue? If so we should spread the word about this repo. But are we even allowed to?  tjmarkham has the license for it and I tried contacting him but he isn't responding.

**Comment by MinhThienDX** [comment]
`I'm relatively new to Git.`
Everyone has to start some where, learn as you go. 🤞
Actually, my suggestion is not only apply to git, just break big pile into smaller things, that will make stuffs more manageable and easier to overcome procrastination (yeah seriously, it is life hacks)

`Do you think the work on Win10Widgets is something we should even continue?`
Therer is only 1 time we stop: When we don't use this anymore.
I am not telling you to focus in this, just make adjustments to fit your need.
You have things to do too.

`If so we should spread the word about this repo.`
Ok, you can do that if you want. 👍

`But are we even allowed to?`
Think of it like this: Are we forbidden from doing that? 😉
This quote is on point: `"It is often easier to ask for forgiveness than to ask for permission."`

`tjmarkham has the license for it and I tried contacting him but he isn't responding.`
What license 😂
Honestly, his repo does not have any information about license so I don't really know.
However, it is open source, that's what I know for sure.
Yeah about contacting him, I fear that he maybe not with us anymore (I mean maybe just maybe he is dead).
He did a great job, but he abandoned it so we are unofficially his maintainer.
And let this project rot is simply too wasteful.
Don't worry too much, this happen a lot more often than you think. [https://softwareengineering.stackexchange.com/questions/273156/how-should-i-contribute-to-a-mostly-abandoned-github-project](url)
It's not like we stole his repo while he is absent for 3 weeks on a vacation or something. (Yes that did happen to someone)

**Comment by Kablion** [comment]
> I am not telling you to focus in this, just make adjustments to fit your need.
> You have things to do too.

It's fun for me to try git+rainmeter and I like these skins. :)

> Yeah about contacting him, I fear that he maybe not with us anymore (I mean maybe just maybe he is dead).

I don't think so. He updated the original repo on 12 April. [https://github.com/tjmarkham/win10widgets/commit/0982c71e37798283534061f8c0ffcb2865ff2fc6](url)

> He did a great job, but he abandoned it so we are unofficially his maintainer.
> And let this project rot is simply too wasteful.

I think so too.

**Comment by MinhThienDX** [comment]
> It's fun for me to try git+rainmeter and I like these skins. :)

Glad to hear that you are having fun, also not much people use rainmeter with git to update skin.

> I don't think so. He updated the original repo on 12 April. [This Commit](https://github.com/tjmarkham/win10widgets/commit/0982c71e37798283534061f8c0ffcb2865ff2fc6)

😂 Then he abandoned it.
How can one NOT see all the email GitHub send when someone interact with your repo?

**Pull request merged**
